### ISSUE TITLE
pidgey pidgey pidgey pidgey pidgey pidgey 

### ISSUE THREAD

**Issue by JakeChampion** [quarterto/slack-pokedex#1]
pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey pidgey

**Comment by gitGremlin** [comment]
won't fix

**Comment by jonathan-best** [comment]
![](http://pokeapi.co/media/sprites/pokemon/16.png)![](http://pokeapi.co/media/sprites/pokemon/16.png)![](http://pokeapi.co/media/sprites/pokemon/16.png)![](http://pokeapi.co/media/sprites/pokemon/16.png)![](http://pokeapi.co/media/sprites/pokemon/16.png)![](http://pokeapi.co/media/sprites/pokemon/16.png)![](http://pokeapi.co/media/sprites/pokemon/16.png)![](http://pokeapi.co/media/sprites/pokemon/16.png)![](http://pokeapi.co/media/sprites/pokemon/16.png)![](http://pokeapi.co/media/sprites/pokemon/16.png)![](http://pokeapi.co/media/sprites/pokemon/16.png)![](http://pokeapi.co/media/sprites/pokemon/16.png)
